### ISSUE TITLE
Implement endianness

### ISSUE THREAD

**Issue by Reokodoku** [Arnau478/hevi#35]
How about printing hexadecimal numbers based on the system endianness or the specified endianness when the `--no-ascii` flag is specified?

This can be useful.

**Comment by Arnau478** [comment]
How can it be beneficial? I don't get it...

**Comment by Reokodoku** [comment]
If someone needs to see the "real" binary, it would be better to see it with the right endianness.

For example, someone could see if he had "written" with the correct endianness the magic number of the MBR.

Also, this could be used with the future `--raw` flag.

**Comment by Arnau478** [comment]
But there's no endianness here, it's all bytes... There's no byte ordering because there's no multi-byte data. Doing so would also require to know the start offset of the multi-byte integer, which is impossible to do for hevi.

**Comment by Arnau478** [comment]
I don't think this makes much sense. I don't get what you're trying to propose. If you want to explain a bit more about what this proposal is about, you're welcome to do so. Until then, I'll be closing this issue.
