### ISSUE TITLE
Update AUR package

### ISSUE THREAD

**Issue by Arnau478** [Arnau478/hevi#47]
The `hevi-bin` AUR package is outdated (it's still `0.2.0`). It would also be nice to have a `hevi` package that built it from source.

**Comment by Reokodoku** [comment]
Maybe we can automatically update `hevi-bin` with some GitHub actions (if they exist).

**Comment by Arnau478** [comment]
> Maybe we can automatically update `hevi-bin` with some GitHub actions (if they exist).

Don't think so, it requires the maintainer to authenticate via SSH keys iirc

**Comment by ATTron** [comment]
oh i actually just did this and didnt realize there was an issue out for this. It lives here https://aur.archlinux.org/packages/hevi

**Comment by Arnau478** [comment]
Nice, thanks! Although I'm pretty sure it should have had the `-bin` suffix? Either way, thanks! :)
